codetouch/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('messenger.urls')),
    url(r'^admin/', admin.site.urls),
]

messenger/urls.py
from django.conf.urls import url

from . import views

app_name = 'messenger'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^webchat/$', views.webchat, name='webchat'),
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^signout/$', views.signout, name='signout')

]

messenger/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Message(models.Model):
    message_text = models.CharField(max_length=2000)
    sentOn = models.DateTimeField('Sent On')
    sender = models.CharField(max_length=150, default='None')
    reciever = models.CharField(max_length=150, default='None')

    def __str__(self):
        return self.message_text

messenger/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Message
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.sessions.models import Session
from django.utils import timezone
import datetime


def index(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('messenger:webchat'))

    return render(request, 'messenger/index.html')


def signin(request):
    user = authenticate(username=request.POST.get('username'), password=request.POST.get('password'))
    if user is not None:
        login(request, user)
        request.session.set_expiry(0)  # Expire session on browser close
        return HttpResponseRedirect(reverse('messenger:webchat'))
    else:
        context = {'error_message': 'Login Failed'}
        return render(request, 'messenger/index.html', context)


def signup(request):
    first_name = request.POST.get('fname')
    last_name = request.POST.get('lname')
    username = request.POST.get('username')
    password = request.POST.get('password')
    email = request.POST.get('email')

    # Check for duplicate username
    try:
        u = User.objects.get(username=username)
    except User.DoesNotExist:
        u = None

    # Check for duplicate email
    try:
        e = User.objects.get(email=email)
    except User.DoesNotExist:
        e = None

    if u is not None:
        context = {'error_message': 'User Exists'}
        return render(request, 'messenger/index.html', context)

    if e is not None:
        context = {'error_message': 'Email Exists'}
        return render(request, 'messenger/index.html', context)

    user = User.objects.create_user(first_name=first_name, last_name=last_name,
                                    username=username, password=password,
                                    email=email)

    context = {'user_created': 'User Created'}
    return render(request, 'messenger/index.html', context)


def datetime_handler(x):
    if isinstance(x, datetime.datetime):
        time = str(x.hour)+":"+str(x.minute)+":"+str(x.second)
        # return x.isoformat()
        return time
    raise TypeError("Unknown type")

@login_required(login_url='/')
def webchat(request):
    secondary_user = request.POST.get('secondary_user')
    message_text = request.POST.get('message')

    if message_text:
        message = Message(message_text=message_text,
                          sentOn=timezone.now(),
                          sender=request.user,
                          reciever=secondary_user)
        message.save()

    sessions = Session.objects.filter(expire_date__gte=timezone.now())
    uid_list = []

    # Build a list of user ids from that query
    for session in sessions:
        data = session.get_decoded()
        uid_list.append(data.get('_auth_user_id', None))

    # Query all logged in users based on id list
    online_users = User.objects.filter(id__in=uid_list)
    offline_users = []
    users = User.objects.all()
    for user in users:
        if user not in online_users:
            offline_users.append(user)

    recieved_messages = Message.objects.filter(reciever=request.user, sender=secondary_user).values()
    sent_messages = Message.objects.filter(sender=request.user, reciever=secondary_user).values()

    if recieved_messages is None and sent_messages is None:
        context = {'online_users': online_users,
                   'offline_users': offline_users,
                   'main_user': request.user,
                   'No Messages': 'Send a message now to begin the conversation'}

        return render(request, 'messenger/webchat.html', context)

    messages = recieved_messages | sent_messages
    messages = messages.order_by('sentOn')
    context = {'online_users': online_users,
               'offline_users': offline_users,
               'main_user': request.user,
               'secondary_user': secondary_user,
               'Messages': messages}

    if request.is_ajax() and request.method == 'POST':
        context = {'Messages': messages, 'secondary_user': secondary_user, 'main_user': request.user}
        return render(request, 'messenger/chatbody.html', context)
        # return render(request, 'messenger/webchat.html', context)
    else:
        return render(request, 'messenger/webchat.html', context)


def signout(request):
    logout(request)
    return HttpResponseRedirect(reverse('messenger:index'))

messenger/templates/messenger/chatbody.html
<div id="chat-messages">
{% for message in Messages %}
                {% if message.sender == main_user.username  %}
                    <div class="message right">
                    <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/245657/1_copy.jpg" />
                {% else %}
                    <div class="message">
                    <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/245657/2_copy.jpg" />
                {% endif %}

                <div class="bubble">
                	{{ message.message_text }}
                    <div class="corner"></div>
                    <span>{{ message.sentOn.time }}</span>
                </div>
            </div>
{% endfor %}
    </div></div>

messenger/templates/messenger/index.html
<!DOCTYPE html>
<html >
{% load static %}
<head>
  <meta charset="UTF-8">
  <title>Codetouch Messenger</title>
  <link href='https://fonts.googleapis.com/css?family=Titillium+Web:400,300,600' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
  <link rel="stylesheet" href="{% static 'messenger/css/style.css' %}">
  
</head>

<body>
  <div class="form">
      
      <ul class="tab-group">
          <li class="tab active"><a href="#login">Log In</a></li>
          <li class="tab"><a href="#signup">Sign Up</a></li>
      </ul>
      
      <div class="tab-content">
      <div id="login">
      {% if error_message %}
          <h1 style="color:red">{{ error_message }}</h1>
      {% elif user_created %}
          <h1>{{ user_created }}</h1>
      {% else %}
          <h1>Welcome Back!</h1>
      {% endif %}

          <form action="{% url 'messenger:signin' %}" method="post">
          {% csrf_token %}
            <div class="field-wrap">
            <label>
              Username<span class="req">*</span>
            </label>
            <input type="text"required autocomplete="off" name="username"/>
          </div>

          <div class="field-wrap">
            <label>
              Password<span class="req">*</span>
            </label>
            <input type="password"required autocomplete="off" name="password"/>
          </div>

          <p class="forgot" hidden="hidden"><a href="#">Forgot Password?</a></p>

          <button type="Submit" name="action" value="signin" class="button button-block"/>Log In</button>

          </form>

        </div>

        <div id="signup">
             <h1>Sign Up</h1>

          <form action="{% url 'messenger:signup' %}" method="post">
          {% csrf_token %}
          <div class="top-row">
            <div class="field-wrap">
              <label>
                First Name<span class="req">*</span>
              </label>
              <input name="fname" type="text" required autocomplete="off" />
            </div>
        
            <div class="field-wrap">
              <label>
                Last Name<span class="req">*</span>
              </label>
              <input name="lname" type="text"required autocomplete="off"/>
            </div>
          </div>

          <div class="field-wrap">
            <label>
              Username<span class="req">*</span>
            </label>
            <input name="username" type="text"required autocomplete="off"/>
          </div>

          <div class="field-wrap">
            <label>
              Email Address<span class="req">*</span>
            </label>
            <input name="email" type="email"required autocomplete="off"/>
          </div>
          
          <div class="field-wrap">
            <label>
              Set A Password<span class="req">*</span>
            </label>
            <input name="password" type="password"required autocomplete="off"/>
          </div>
          
          <button type="submit" name="action" value="signup" class="button button-block"/>Sign up</button>
          
          </form>

        </div>
        
      </div><!-- tab-content -->
      
</div> <!-- /form -->
  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

    <script src="{% static 'messenger/js/index.js' %}"></script>

</body>
</html>

messenger/templates/messenger/webchat.html
<!DOCTYPE html>
<html >
{% load static %}
  <head>
    <meta charset="UTF-8">
    <title>Codetouch Messenger</title>
{#          <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">#}
        <link rel="stylesheet" href="{% static 'messenger/css/webchat.css' %}">

  </head>

  <body>
    <input id="csrf_token" value="{{ csrf_token }}" type="hidden"/>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>

<div id="chatbox">
	<div id="friendslist">
    	<div id="topmenu">
        	<span class="friends"></span>
            <span class="chats"></span>
            <input id='logoutPath' type="hidden" value="{% url 'messenger:signout' %}">
            <form id="logoutForm" action="{% url 'messenger:signout' %}" method="post">
                {% csrf_token %}
                <span class="history"  onclick="logUserOut()" style="background: url({% static 'messenger/images/logout.png' %});
                background-size: 40% 40%;
                background-repeat: no-repeat;
                position: relative;
                left: 34px;
                top: 22px;"></span>
            </form>

        </div>
        
        <div id="friends">
            {% for user in online_users %}
                    {% if user.username != main_user.username %}
                        <div class="friend" id="{{ user.username }}">
                            <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/245657/1_copy.jpg" />
                            <p>
                                <strong>{{ user.username }}</strong>
                                <span>{{ user.email }}</span>
                            </p>
                            <div class="status available"></div>
                        </div>
                    {% endif %}
            {% endfor %}

            {% for user in offline_users %}
                <div class="friend" id="{{ user.username }}">
                    <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/245657/1_copy.jpg" />
                    <p>
                        <strong>{{ user.username }}</strong>
                        <span>{{ user.email }}</span>
                    </p>
                    <div class="status inactive"></div>
                </div>
            {% endfor %}
{#            <div id="search">#}
{#	            <input type="text" id="searchfield" value="Search contacts..." />#}
{#            </div>#}
            
        </div>                
        
    </div>	
    
    <div id="chatview" class="p1">    	
        <div id="profile">

            <div id="close">
                <div class="cy"></div>
                <div class="cx"></div>
            </div>
            
            <p>{{ secondary_user }}</p>
            <span>miro@badev@gmail.com</span>
        </div>

        <div id="chat-messages">
{#        	<label>Thursday 02</label>#}
            {% include 'messenger/chatbody.html' %}
        </div>
        <div id="sendmessage">
            <form method="post" action="{% url 'messenger:webchat' %}" id = "submitMessage">
                {% csrf_token %}
        	<input type="text" value="Send message..." name="message" id="message"/>
            <input type="hidden" id="secondary_user" name="secondary_user" value=""/>
            <button type="Submit" name="action"></button>
            </form>
        </div>

    </div>        
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script src="{% static 'messenger/js/webchat.js' %}"></script>
<script>

    $("#logoutForm").click(function(){

    });
    logUserOut = function() {
        form = document.getElementById('logoutForm')
        form.submit()

    };
	$(".friend").each(function(){
		$(this).click(function(){
			document.getElementById('secondary_user').value = this.id;
			console.log(this.id);

			$.ajax({
            url: '{% url 'messenger:webchat' %}',
            type: "POST",
            method: "POST",
            data: {
                'secondary_user': document.getElementById('secondary_user').value,
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            success: function(response) {
                $("#chat-messages").replaceWith(response);
            },
            failure: function(response) {
                alert('Got an error dude');
            }
        });

			var childOffset = $(this).offset();
			var parentOffset = $(this).parent().parent().offset();
			var childTop = childOffset.top - parentOffset.top;
			var clone = $(this).find('img').eq(0).clone();
			var top = childTop+12+"px";

			$(clone).css({'top': top}).addClass("floatingImg").appendTo("#chatbox");

			setTimeout(function(){$("#profile p").addClass("animate");$("#profile").addClass("animate");}, 100);
			setTimeout(function(){
				$("#chat-messages").addClass("animate");
				$('.cx, .cy').addClass('s1');
				setTimeout(function(){$('.cx, .cy').addClass('s2');}, 100);
				setTimeout(function(){$('.cx, .cy').addClass('s3');}, 200);
			}, 150);

			$('.floatingImg').animate({
				'width': "68px",
				'left':'108px',
				'top':'20px'
			}, 200);

			var name = $(this).find("p strong").html();
			var email = $(this).find("p span").html();
			$("#profile p").html(name);
			$("#profile span").html(email);

			$(".message").not(".right").find("img").attr("src", $(clone).attr("src"));
			$('#friendslist').fadeOut();
			$('#chatview').fadeIn();


			$('#close').unbind("click").click(function(){
				$("#chat-messages, #profile, #profile p").removeClass("animate");
				$('.cx, .cy').removeClass("s1 s2 s3");
				$('.floatingImg').animate({
					'width': "40px",
					'top':top,
					'left': '12px'
				}, 200, function(){$('.floatingImg').remove()});

				setTimeout(function(){
					$('#chatview').fadeOut();
					$('#friendslist').fadeIn();
				}, 50);
			});

		});
	});
    </script>
  </body>
</html>